#!/bin/bash

if [ ! -e "$1" ]; then
	echo "USAGE: $0 file.<apk|dex>"
	exit 1
fi

FILE=`echo "$1" |sed -e "s/.apk$//gI" -e"s/.dex$//gI"`
CURPATH=`pwd`
TMPDIR="/tmp/apk2java.$$"

dex2jar "${1}"

mkdir -p "${TMPDIR}"
mv "${FILE}.jar" "${TMPDIR}/"
cd "${TMPDIR}"
unzip "${TMPDIR}/${FILE}.jar"
rm "${TMPDIR}/${FILE}.jar"
for d in `find . -iname "*.class" |xargs -n 1 dirname |uniq` ; do 
	cd ${d}
	jad *.class
	rm *.class
	for j in `ls *.jad` ; do
		t=`echo $j |sed -e "s/.jad$/.java/g"`
		mv ${j} ${t}
	done
	cd ${TMPDIR}
done
mkdir -p "${CURPATH}/${FILE}/java/"
mv * "${CURPATH}/${FILE}/java/"
cd "${CURPATH}"
rm -r "${TMPDIR}"
