#!/bin/bash

if [ ! -e "$1" ]; then
	echo "USAGE: $0 file.<apk|dex>"
	exit 1
fi

FILE=`echo "$1" |sed -e "s/.apk$//gI" -e"s/.dex$//gI"`
echo "FILE: $FILE"
CURPATH=`pwd`
TMPDIR="/tmp/dex2jar.$$"

mkdir -p "${TMPDIR}"

/home/pau/bin/dex2jar-src/d2j-dex2jar.sh -s -f -o ${FILE}.jar "$1" 2>&1 |tee -a ${TMPDIR}/dex2jar.out
cat ${TMPDIR}/dex2jar.out |grep "Exception" >/dev/null
if [ $? == 0 ]; then
	echo "dex2jar failed - trying with older version"
	# dex2jar version: reader-1.3, translator-0.0.9.2-SNAPSHOT, ir-1.0
	# this should work with APK that have been hosed with hosedex2jar http://www.decompilingandroid.com/hosedex2jar/
	cd ${TMPDIR}
	unzip "${CURPATH}/${1}" classes.dex
	/home/pau/bin/dex-translator-0.0.9.2-SNAPSHOT/dex2jar.sh ${TMPDIR}/classes.dex
	mv classes_dex2jar.jar "${CURPATH}/${FILE}.jar"
fi
cd ${CURPATH}
rm -rf ${TMPDIR}
